/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoxNFT } from "./BoxNFT";
export type { FragmentNFT } from "./FragmentNFT";
export type { TicketMarketplace } from "./TicketMarketplace";
export type { TicketNFT } from "./TicketNFT";
